/*
 * This file is generated by jOOQ.
 */
package com.example.technicaltest.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AiAnalysisLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer    id;
    private final String     imagePath;
    private final String     success;
    private final String     message;
    private final Integer    class_;
    private final BigDecimal confidence;
    private final UInteger   requestTimestamp;
    private final UInteger   responseTimestamp;

    public AiAnalysisLog(AiAnalysisLog value) {
        this.id = value.id;
        this.imagePath = value.imagePath;
        this.success = value.success;
        this.message = value.message;
        this.class_ = value.class_;
        this.confidence = value.confidence;
        this.requestTimestamp = value.requestTimestamp;
        this.responseTimestamp = value.responseTimestamp;
    }

    public AiAnalysisLog(
        Integer    id,
        String     imagePath,
        String     success,
        String     message,
        Integer    class_,
        BigDecimal confidence,
        UInteger   requestTimestamp,
        UInteger   responseTimestamp
    ) {
        this.id = id;
        this.imagePath = imagePath;
        this.success = success;
        this.message = message;
        this.class_ = class_;
        this.confidence = confidence;
        this.requestTimestamp = requestTimestamp;
        this.responseTimestamp = responseTimestamp;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.image_path</code>.
     */
    public String getImagePath() {
        return this.imagePath;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.success</code>.
     */
    public String getSuccess() {
        return this.success;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.message</code>.
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.class</code>.
     */
    public Integer getClass_() {
        return this.class_;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.confidence</code>.
     */
    public BigDecimal getConfidence() {
        return this.confidence;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.request_timestamp</code>.
     */
    public UInteger getRequestTimestamp() {
        return this.requestTimestamp;
    }

    /**
     * Getter for <code>technical_test.ai_analysis_log.response_timestamp</code>.
     */
    public UInteger getResponseTimestamp() {
        return this.responseTimestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AiAnalysisLog (");

        sb.append(id);
        sb.append(", ").append(imagePath);
        sb.append(", ").append(success);
        sb.append(", ").append(message);
        sb.append(", ").append(class_);
        sb.append(", ").append(confidence);
        sb.append(", ").append(requestTimestamp);
        sb.append(", ").append(responseTimestamp);

        sb.append(")");
        return sb.toString();
    }
}
