/*
 * This file is generated by jOOQ.
 */
package com.example.technicaltest.jooq;


import com.example.technicaltest.jooq.tables.AiAnalysisLog;
import com.example.technicaltest.jooq.tables.records.AiAnalysisLogRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * technical_test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AiAnalysisLogRecord> KEY_AI_ANALYSIS_LOG_PRIMARY = Internal.createUniqueKey(AiAnalysisLog.AI_ANALYSIS_LOG, DSL.name("KEY_ai_analysis_log_PRIMARY"), new TableField[] { AiAnalysisLog.AI_ANALYSIS_LOG.ID }, true);
}
