/*
 * This file is generated by jOOQ.
 */
package com.example.technicaltest.jooq;


import com.example.technicaltest.jooq.tables.AiAnalysisLog;


/**
 * Convenience access to all tables in technical_test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>technical_test.ai_analysis_log</code>.
     */
    public static final AiAnalysisLog AI_ANALYSIS_LOG = AiAnalysisLog.AI_ANALYSIS_LOG;
}
